// Isolated PostgreSQL execution. Never connects to an application database.
// npm install --prefix build/sql-validation --no-audit --no-fund @electric-sql/pglite
import { PGlite } from '../../build/sql-validation/node_modules/@electric-sql/pglite/dist/index.js';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
let checks = 0;
const check = (a,b,label) => { assert.deepEqual(a,b,label); checks++; };
const read = p => readFileSync(new URL(p,import.meta.url),'utf8');
const scalar = async (sql,params=[]) => Object.values((await db.query(sql,params)).rows[0])[0];
const id = n => `00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const tourist=id(1), driverA=id(2), driverB=id(3), outsider=id(4), booking=id(10), solo=id(11), a=id(20), b=id(21);
const count = (type,user=tourist) => scalar('select count(*)::int from notifications where type=$1 and user_id=$2',[type,user]);
try {
  await db.exec(read('./event_driven_trip_fixture.sql'));
  await db.exec(`
    create role service_role bypassrls;
    alter table profiles add column city text;
    alter table profiles add column is_online boolean default true;
    alter table profiles add column is_available boolean default true;
    alter table package_bookings add column municipality text;
    alter table package_bookings add column pickup_address text;
    alter table payment_records add column provider text default 'paymongo';
    alter table payment_records add column provider_status text;
    alter table payment_records add constraint actual_payment_status check(status in ('pending_confirmation','confirmed','disputed','cancelled'));
    alter table notifications add column id bigint generated always as identity primary key;
    alter table notifications add column created_at timestamptz default now();
    alter table notifications enable row level security;
    grant usage on schema public,auth to authenticated,anon,service_role;
    grant select,update on notifications to authenticated;
    create policy notifications_update_own on notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
    create table emergency_alerts(id uuid primary key,tourist_id uuid,booking_id uuid,driver_id uuid,alert_status text default 'active');
    create function required_booking_driver_roster(uuid) returns setof booking_drivers language sql stable as $$
      select * from booking_drivers where booking_id=$1 and status in ('accepted','completed') order by accepted_at,id $$;
  `);
  const availableSource=read('../migrations/20260830000000_booking_schedule_group_chat_arrivals.sql');
  const availableStart=availableSource.indexOf('create or replace function public.notify_drivers_of_available_booking()');
  await db.exec(availableSource.slice(availableStart,availableSource.indexOf('$$;',availableStart)+3));
  await db.exec('create trigger trg_notify_available_package_job after insert on package_bookings for each row execute function notify_drivers_of_available_booking()');
  await db.exec(read('../migrations/20260924000000_notification_delivery.sql'));
  await db.exec('create policy "Authenticated users can create notifications" on notifications for insert to authenticated with check(true)');
  await db.exec(read('../migrations/20260925000000_notification_runtime_diagnostics.sql'));
  check(await scalar("select count(*)::int from pg_policies where tablename='notifications' and policyname='Authenticated users can create notifications'"),0,'remote legacy permissive insertion policy removed');
  await db.query(`insert into profiles(id,role,city) values($1,'tourist','Baliwag'),($2,'driver','Baliwag'),($3,'driver','Baliwag'),($4,'tourist','Baliwag')`,[tourist,driverA,driverB,outsider]);
  await db.query("select set_config('test.uid',$1,false)",[tourist]);
  await db.query('select register_notification_device($1,$2)',[id(99),'test-token-12345678901234567890']);
  check((await scalar('select notification_device_status($1)',[id(99)])).registered,true,'registration is verified without returning a token');
  await db.query("insert into package_bookings(id,tourist_id,status,booking_status,municipality) values($1,$2,'pending','waiting_for_drivers','Baliwag')",[booking,tourist]);
  check(await count('booking_submitted'),1,'booking submission persisted');
  check(await count('available_package_job',driverA),1,'existing eligible driver dispatch retained');
  check(await count('available_package_job',outsider),0,'jobs are not broadcast to unrelated users');
  check(await scalar('select count(*)::int from notification_deliveries'),0,'self submission is center only');
  await db.query("insert into booking_drivers(id,booking_id,driver_id,status,journey_state) values($1,$2,$3,'accepted','assigned'),($4,$2,$5,'accepted','assigned')",[a,booking,driverA,b,driverB]);
  check(await count('booking_confirmed'),1,'multi-row assignment has one aggregate confirmation');
  check(await count('drivers_assigned'),1,'aggregate assignment history');
  await db.query("update booking_drivers set journey_state='en_route_pickup' where booking_id=$1",[booking]);
  check(await count('driver_on_the_way'),1,'convoy on the way once');
  await db.query("update booking_drivers set journey_state='en_route_pickup' where booking_id=$1",[booking]);
  check(await count('driver_on_the_way'),1,'unchanged state is silent');
  const beforeGPS=await scalar('select count(*)::int from notifications');
  await db.query('insert into driver_live_locations(driver_id,latitude,longitude) values($1,15,121)',[driverA]);
  await db.query('update driver_live_locations set latitude=15.001 where driver_id=$1',[driverA]);
  await db.query("update package_bookings set estimated_end_at=now()+interval '2 hours' where id=$1",[booking]);
  check(await scalar('select count(*)::int from notifications'),beforeGPS,'GPS and ETA are silent');
  await db.query("update booking_drivers set journey_state='at_pickup' where id=$1",[a]);
  check(await count('driver_arrived'),1,'partial arrival history');
  check(await scalar("select body from notifications where type='driver_arrived'"),'1 of 2 drivers have arrived at the pickup point.','correct partial copy');
  check(await count('drivers_arrived'),0,'one driver cannot claim all arrived');
  check(await scalar("select push_enabled from notifications where type='driver_arrived'"),false,'partial arrival does not spam push');
  await db.query("update booking_drivers set journey_state='at_pickup' where id=$1",[b]);
  check(await count('drivers_arrived'),1,'all-driver aggregate arrival');
  await db.query("update booking_drivers set journey_state='boarded' where booking_id=$1",[booking]);
  check(await count('tour_started'),1,'tour started aggregate');
  await db.query("insert into booking_itinerary_items(id,booking_id,destination_name,order_number) values($1,$2,'Barasoain Church',1),($3,$2,'Museum',2)",[id(30),booking,id(31)]);
  for(const state of ['en_route_stop','at_stop','stop_done']) {
    await db.query('update booking_drivers set journey_state=$1 where booking_id=$2',[state,booking]);
  }
  check(await count('spot_arrived'),1,'GPS-confirmed stop transition creates one aggregate');
  await db.query('insert into booking_driver_arrivals(booking_driver_id,itinerary_item_id) values($1,$2),($3,$2)',[a,id(30),b]);
  check(await count('spot_arrived'),1,'arrival table and journey events share one idempotency key');
  check(await count('spot_completed'),0,'no redundant completion alert');
  await db.query("update booking_drivers set current_stop_index=1,journey_state='en_route_stop' where booking_id=$1",[booking]);
  check(await count('heading_to_spot'),2,'one heading notification per destination');
  check(await scalar("select title from notifications where type='heading_to_spot' order by id desc limit 1"),'Next Destination','next destination copy');
  await db.query('insert into booking_driver_arrivals(booking_driver_id,itinerary_item_id) values($1,$2)',[a,id(31)]);
  check(await count('spot_arrived'),1,'fallback GPS arrival waits for full roster');
  await db.query('insert into booking_driver_arrivals(booking_driver_id,itinerary_item_id) values($1,$2)',[b,id(31)]);
  check(await count('spot_arrived'),2,'fallback GPS RPC creates aggregate arrival without journey mutation');
  await db.query("insert into booking_payment_requirements(booking_id,payment_stage,status,amount) values($1,'down_payment','required',3600)",[booking]);
  check(await count('down_payment_required'),1,'downpayment action');
  await db.query("update package_bookings set booking_status='awaiting_remaining_payment' where id=$1",[booking]);
  check(await count('remaining_payment_required'),1,'remaining payment due only at real gate');
  await db.query("insert into payment_records(id,booking_id,status,payment_stage) values($1,$2,'pending_confirmation','down_payment')",[id(40),booking]);
  await db.query("update payment_records set status='confirmed' where id=$1",[id(40)]);
  await db.query("update payment_records set status='confirmed' where id=$1",[id(40)]);
  check(await count('payment_confirmed'),1,'confirmed webhook retry deduplicates');
  check(await count('payment_confirmed',driverA),1,'downpayment reaches required driver');
  await db.query("insert into payment_records(id,booking_id,status,payment_stage,provider_status) values($1,$2,'cancelled','remaining_balance','failed')",[id(41),booking]);
  check(await count('payment_failed'),1,'actionable payment failure');
  await db.query("insert into payment_records(id,booking_id,status,payment_stage,provider_status) values($1,$2,'pending_confirmation','remaining_balance','creating_checkout')",[id(42),booking]);
  check(await count('payment_failed'),1,'intermediate provider state is silent');
  await db.query("update payment_records set provider_status='checkout_failed' where id=$1",[id(42)]);
  check(await count('payment_failed'),2,'checkout failure notifies even if payment status is unchanged');
  await db.query("insert into payment_allocations(payment_record_id,driver_id,status) values($1,$2,'awaiting_cash')",[id(41),driverA]);
  check(await count('cash_confirmation_required',driverA),1,'cash request targets required payee');
  check(await count('cash_confirmation_required',driverB),0,'unrelated driver does not get cash request');
  await db.query("insert into emergency_alerts(id,tourist_id,booking_id) values($1,$2,$3) on conflict do nothing",[id(50),tourist,booking]);
  await db.query("insert into emergency_alerts(id,tourist_id,booking_id) values($1,$2,$3) on conflict do nothing",[id(50),tourist,booking]);
  check(await count('emergency_alert',driverA),1,'emergency retry deduplicates');
  await db.query("insert into emergency_alerts(id,tourist_id,booking_id) values($1,$2,$3)",[id(51),outsider,booking]);
  check(await count('emergency_alert',driverA),1,'forged booking association cannot notify');
  await db.query("update booking_drivers set journey_state='en_route_dropoff' where booking_id=$1",[booking]);
  await db.query("update booking_drivers set journey_state='at_dropoff' where booking_id=$1",[booking]);
  check(await count('heading_dropoff'),1,'heading dropoff'); check(await count('arrived_dropoff'),1,'arrival dropoff');
  await db.query("update package_bookings set booking_status='completed',status='completed' where id=$1",[booking]);
  check(await count('tour_completed'),1,'tour complete once');
  await db.query("insert into package_bookings(id,tourist_id,status,booking_status,required_drivers) values($1,$2,'pending','waiting_for_drivers',1)",[solo,tourist]);
  await db.query("insert into booking_drivers(id,booking_id,driver_id,status,journey_state) values($1,$2,$3,'accepted','assigned')",[id(22),solo,driverA]);
  await db.query("update booking_drivers set journey_state='at_pickup' where booking_id=$1",[solo]);
  check(await scalar("select title from notifications where type='drivers_arrived' and booking_id=$1",[solo]),'Driver Arrived','solo copy');
  await db.query("update package_bookings set status='cancelled',booking_status='cancelled' where id=$1",[solo]);
  check(await count('booking_cancelled'),1,'cancellation persists');
  await db.query("insert into notifications(user_id,title,type) values($1,'Legacy duplicate','booking_cancelled')",[tourist]);
  check(await count('booking_cancelled'),1,'legacy cancellation suppressed');
  await db.query("insert into notifications(user_id,title,type) values($1,'Legacy duplicate','itinerary_arrival')",[tourist]);
  check(await count('itinerary_arrival'),0,'legacy per-driver arrivals suppressed');
  const ownId=await scalar('select id::text from notifications where user_id=$1 limit 1',[tourist]);
  check((await scalar('select notification_destination($1)',[ownId])).screen,'tourist_booking','authorized destination');
  await db.query("select set_config('test.uid',$1,false)",[outsider]);
  await db.exec('set role authenticated');
  check(await scalar('select count(*)::int from notifications'),0,'RLS prevents cross-user reads');
  check(await scalar('select notification_destination($1)',[ownId]),null,'forged deep link rejected');
  await db.query('update notifications set is_read=true where id::text=$1',[ownId]);
  await assert.rejects(()=>db.query('update notifications set title=$1',['Forged'])); checks++;
  await assert.rejects(()=>db.query("select emit_tour_notification($1,$2,'forged','x','x','x')",[tourist,booking])); checks++;
  await db.exec('reset role');
  check(await scalar('select is_read from notifications where id::text=$1',[ownId]),false,'cross-user read mutation ignored');
  await db.query("select set_config('test.uid',$1,false)",[tourist]);
  await db.exec('set role authenticated');
  await db.query('update notifications set is_read=true,read_at=now() where id::text=$1',[ownId]);
  check(await scalar('select is_read from notifications where id::text=$1',[ownId]),true,'own read mutation allowed');
  await db.exec('reset role');
  const jobs=(await db.query('select * from claim_notification_deliveries(100)')).rows;
  assert(jobs.length>0); checks++;
  check((await db.query('select * from claim_notification_deliveries(100)')).rows.length,0,'lease prevents double claim');
  const job=jobs[0];
  await db.query("select finish_notification_delivery($1,$2,'retry','HTTP_503')",[job.delivery_id,job.lease_id]);
  check(await scalar('select status from notification_deliveries where id=$1',[job.delivery_id]),'pending','provider outage retries');
  check(await scalar('select status from package_bookings where id=$1',[booking]),'completed','provider outage never rolls back tour');
  await db.query("select finish_notification_delivery($1,$2,'sent')",[job.delivery_id,id(777)]);
  check(await scalar('select status from notification_deliveries where id=$1',[job.delivery_id]),'pending','stale lease cannot ack');
  const invalid=jobs[1];
  await db.query("select finish_notification_delivery($1,$2,'invalid','UNREGISTERED')",[invalid.delivery_id,invalid.lease_id]);
  check(await scalar('select active from notification_devices where installation_id=$1',[id(99)]),false,'invalid token disabled');
  await db.query('select claim_notification_deliveries(100)');
  check(await scalar('select status from notification_deliveries where id=$1',[job.delivery_id]),'skipped','stale device jobs skipped');
  await db.query('select register_notification_device($1,$2)',[id(99),'refreshed-token-12345678901234567890']);
  await db.query("insert into package_bookings(id,tourist_id,status,booking_status,required_drivers) values($1,$2,'pending','waiting_for_drivers',1)",[id(70),tourist]);
  // Inject a provider-queue outage. History and the source transition still commit.
  await db.exec(`create function fail_notification_enqueue() returns trigger language plpgsql as $$ begin raise exception 'SIMULATED_QUEUE_OUTAGE'; end $$;
    create trigger fail_enqueue before insert on notification_deliveries for each row execute function fail_notification_enqueue();`);
  await db.query("update package_bookings set scheduled_start_at=now()+interval '1 day' where id=$1",[id(70)]);
  check(await count('schedule_changed'),1,'history survives queue outage');
  const recoveredId=await scalar("select id::text from notifications where type='schedule_changed' and user_id=$1",[tourist]);
  check(await scalar('select count(*)::int from notification_deliveries where notification_id=$1',[recoveredId]),0,'queue failure isolated');
  await db.exec('drop trigger fail_enqueue on notification_deliveries');
  const recovered=(await db.query('select * from claim_notification_deliveries(100)')).rows;
  check(recovered.some(j=>j.notification_id===recoveredId),true,'worker repairs missing delivery from history');
  await db.exec('create table notification_settings(tourist_id uuid primary key,booking_updates boolean,driver_updates boolean,payment_updates boolean)');
  await db.query('insert into notification_settings values($1,false,true,true)',[tourist]);
  await db.query("update package_bookings set scheduled_start_at=now()+interval '2 days' where id=$1",[id(70)]);
  check(await scalar("select push_enabled from notifications where type='schedule_changed' and user_id=$1 order by id desc limit 1",[tourist]),false,'existing notification opt-out is respected');
  check(await scalar("select in_app_enabled from notifications where type='schedule_changed' and user_id=$1 order by id desc limit 1",[tourist]),true,'foreground event survives Android push opt-out');
  await db.query("select set_config('test.uid',$1,false)",[outsider]);
  check((await scalar('select notification_device_status($1)',[id(99)])).registered,false,'device diagnostics cannot read another account binding');
  await db.query('select register_notification_device($1,$2)',[id(99),'refreshed-token-12345678901234567890']);
  await db.query('select claim_notification_deliveries(100)');
  check(await scalar("select count(*)::int from notification_deliveries where recipient_id=$1 and status in ('pending','sending')",[tourist]),0,'account switch cannot deliver previous user jobs');
  const beforeTestBooking=await scalar('select count(*)::int from notifications');
  await db.query("insert into package_bookings(id,tourist_id,status,booking_status,municipality,test_mode) values($1,$2,'pending','waiting_for_drivers','Baliwag',true)",[id(71),tourist]);
  check(await scalar('select count(*)::int from notifications'),beforeTestBooking,'developer test booking creates no history or dispatch push');
  console.log(`Passed ${checks} notification PostgreSQL checks.`);
} finally { await db.close(); }
