// In-memory PostgreSQL regression; never connects to or mutates a linked project.
import { PGlite } from '../../build/sql-validation/node_modules/@electric-sql/pglite/dist/index.js';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const db = new PGlite();
const actor = '00000000-0000-0000-0000-000000000001';

const values = {
  title: 'Validated Package',
  subtitle: 'Three to six spots',
  city: 'Baliwag',
  price_text: 'PHP 1,500',
  duration_text: '8 hours',
  image_url: '',
  cover_image_url: '',
  status: 'draft',
  description: 'Regression package',
  submitted_by_name: 'Tourism Officer',
  visibility_status: 'hidden',
  estimated_budget: 1500,
  route_distance_km: 12,
};

const spots = (count, firstId = 1) => Array.from({ length: count }, (_, index) => ({
  spot_id: firstId + index,
  sort_order: index,
  estimated_duration_minutes: 60,
  recommended_visit_duration_minutes: 60,
}));

try {
  await db.exec(`
    create schema auth;
    create role anon;
    create role authenticated;
    create function auth.uid() returns uuid language sql stable as $$
      select '${actor}'::uuid
    $$;
    create function public.cities_match(text, text) returns boolean
      language sql immutable as $$
        select lower(trim(coalesce($1, ''))) = lower(trim(coalesce($2, '')))
      $$;

    create table public.tourist_spots(
      id bigint primary key,
      city text not null
    );
    create table public.tour_packages(
      id bigint generated by default as identity primary key,
      title text not null,
      subtitle text,
      city text not null,
      price_text text,
      duration_text text,
      image_url text,
      created_at timestamptz not null default now(),
      status text not null default 'draft',
      description text,
      submitted_by uuid,
      submitted_by_name text,
      updated_at timestamptz not null default now(),
      visibility_status text not null default 'visible',
      estimated_budget numeric(12,2),
      group_size integer,
      route_distance_km numeric(10,2),
      cover_image_url text,
      category_id bigint
    );
    create table public.tour_package_spots(
      package_id bigint not null references public.tour_packages(id) on delete cascade,
      spot_id bigint not null references public.tourist_spots(id) on delete restrict,
      sort_order integer not null default 0,
      created_at timestamptz not null default now(),
      opening_time time,
      closing_time time,
      estimated_arrival_time time,
      estimated_duration_minutes integer not null default 0,
      recommended_visit_duration_minutes integer not null default 0,
      primary key(package_id, spot_id)
    );
    insert into public.tourist_spots(id, city)
    select id, case when id = 8 then 'Other City' else 'Baliwag' end
    from generate_series(1, 8) id;
  `);

  const migration = readFileSync(new URL(
    '../migrations/20261010100000_package_spot_count_bounds.sql',
    import.meta.url,
  ), 'utf8');
  await db.exec(migration);

  const save = (count) => db.query(
    'select public.save_tour_package_with_spots(null, $1::jsonb, $2::jsonb) as id',
    [JSON.stringify(values), JSON.stringify(spots(count))],
  );

  await assert.rejects(() => save(2), /between 3 and 6 spots/);
  assert.equal(
    (await db.query('select count(*)::integer as count from public.tour_packages')).rows[0].count,
    0,
    'failed saves must be atomic',
  );

  const packageId = (await save(3)).rows[0].id;
  assert.equal(
    (await db.query(
      'select count(*)::integer as count from public.tour_package_spots where package_id = $1',
      [packageId],
    )).rows[0].count,
    3,
  );

  await assert.rejects(
    () => db.query(
      'select public.save_tour_package_with_spots($1, $2::jsonb, $3::jsonb)',
      [
        packageId,
        JSON.stringify({ ...values, title: 'Must Roll Back' }),
        JSON.stringify(spots(2)),
      ],
    ),
    /between 3 and 6 spots/,
  );
  assert.equal(
    (await db.query('select title from public.tour_packages where id = $1', [packageId])).rows[0].title,
    values.title,
    'invalid package edits must roll back metadata and spots together',
  );

  await db.query('select public.replace_tour_package_spots($1, $2::jsonb)', [
    packageId,
    JSON.stringify(spots(6)),
  ]);
  await assert.rejects(
    () => db.query('select public.replace_tour_package_spots($1, $2::jsonb)', [
      packageId,
      JSON.stringify(spots(7)),
    ]),
    /between 3 and 6 spots/,
  );
  assert.equal(
    (await db.query(
      'select count(*)::integer as count from public.tour_package_spots where package_id = $1',
      [packageId],
    )).rows[0].count,
    6,
    'rejected replacement must preserve the previous itinerary',
  );

  await db.query('select public.replace_tour_package_spots($1, $2::jsonb)', [
    packageId,
    JSON.stringify(spots(3)),
  ]);
  await assert.rejects(
    () => db.query(
      'delete from public.tour_package_spots where package_id = $1 and spot_id = 1',
      [packageId],
    ),
    /between 3 and 6 spots/,
  );
  assert.equal(
    (await db.query(
      'select count(*)::integer as count from public.tour_package_spots where package_id = $1',
      [packageId],
    )).rows[0].count,
    3,
    'dropping from three to two must roll back',
  );

  await assert.rejects(
    () => db.query('select public.replace_tour_package_spots($1, $2::jsonb)', [
      packageId,
      JSON.stringify([...spots(2), ...spots(1, 8)]),
    ]),
    /package municipality/,
  );

  console.log('PASS: package spot count accepts 3/6, rejects 2/7, rolls back invalid edits, and enforces municipality');
} finally {
  await db.close();
}
