-- TourisTrike core Supabase schema.
-- Apply with the Supabase SQL editor or CLI migrations.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'tourist',
  created_at timestamptz not null default now(),
  first_name text,
  last_name text,
  full_name text,
  mobile text,
  gender text,
  address text,
  profile_image_url text,
  is_online boolean not null default false,
  middle_name text,
  birthdate date,
  barangay text,
  city text,
  province text default 'Bulacan',
  postal_code text,
  constraint profiles_role_check check (
    role in ('tourist', 'driver', 'admin', 'subtenant')
  )
);

create table if not exists public.admin_settings (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  notifications_enabled boolean not null default true,
  package_alerts boolean not null default true,
  tourist_spot_alerts boolean not null default true,
  performance_reports boolean not null default true,
  system_notices boolean not null default true,
  language text not null default 'English',
  show_total_views boolean not null default true,
  show_bookings boolean not null default true,
  show_popular_destinations boolean not null default true,
  show_top_packages boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  table_name text not null,
  record_id text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.city_tenant_registrations (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  city text not null,
  office_name text,
  contact_person text,
  contact_number text,
  email text,
  office_address text,
  status text not null default 'pending',
  submitted_at timestamptz not null default now(),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  rejection_reason text
);

create table if not exists public.subtenant_details (
  id uuid primary key references public.profiles(id) on delete cascade,
  office_name text,
  city text not null,
  province text not null default 'Bulacan',
  contact_person text,
  contact_number text,
  email text,
  office_address text,
  description text,
  logo_url text,
  cover_image_url text,
  verification_status text not null default 'pending',
  is_active boolean not null default false,
  approved_by uuid references public.profiles(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tourism_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  icon text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tourist_spots (
  id bigint generated by default as identity primary key,
  title text not null,
  city text not null,
  latitude double precision,
  longitude double precision,
  rating numeric(3,2) not null default 0,
  image_url text,
  created_at timestamptz not null default now(),
  description text,
  barangay text,
  province text not null default 'Bulacan',
  status text not null default 'active',
  updated_at timestamptz not null default now(),
  category_id bigint references public.tourism_categories(id) on delete set null,
  submitted_by uuid references public.profiles(id) on delete set null,
  verified_by uuid references public.profiles(id) on delete set null,
  verified_at timestamptz,
  verification_status text not null default 'pending'
);

create table if not exists public.tourist_spot_images (
  id bigint generated by default as identity primary key,
  spot_id bigint not null references public.tourist_spots(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  is_cover boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.tourist_spot_views (
  id bigint generated by default as identity primary key,
  spot_id bigint not null references public.tourist_spots(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.tour_packages (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text,
  city text not null,
  price_text text,
  duration_text text,
  image_url text,
  created_at timestamptz not null default now(),
  status text not null default 'draft',
  description text,
  submitted_by uuid references public.profiles(id) on delete set null,
  submitted_by_name text,
  updated_at timestamptz not null default now(),
  visibility_status text not null default 'visible',
  estimated_budget numeric(12,2),
  group_size integer,
  route_distance_km numeric(10,2),
  cover_image_url text,
  category_id bigint references public.tourism_categories(id) on delete set null,
  approved_by uuid references public.profiles(id) on delete set null,
  approved_at timestamptz,
  return_reason text
);

create table if not exists public.tour_package_spots (
  package_id bigint not null references public.tour_packages(id) on delete cascade,
  spot_id bigint not null references public.tourist_spots(id) on delete restrict,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (package_id, spot_id)
);

create table if not exists public.tour_package_days (
  id bigint generated by default as identity primary key,
  package_id bigint not null references public.tour_packages(id) on delete cascade,
  day_number integer not null,
  title text,
  created_at timestamptz not null default now(),
  unique (package_id, day_number)
);

create table if not exists public.tour_package_day_items (
  id bigint generated by default as identity primary key,
  day_id bigint not null references public.tour_package_days(id) on delete cascade,
  spot_id bigint references public.tourist_spots(id) on delete set null,
  time_label text,
  note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.tour_package_views (
  id bigint generated by default as identity primary key,
  package_id bigint not null references public.tour_packages(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.package_bookings (
  id bigint generated by default as identity primary key,
  package_id bigint not null references public.tour_packages(id) on delete restrict,
  tourist_id uuid not null references public.profiles(id) on delete cascade,
  travel_date date not null,
  adults integer not null default 1,
  payment_method text not null default 'cash',
  notes text,
  total_amount numeric(12,2) not null default 0,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  assigned_driver_id uuid references public.profiles(id) on delete set null,
  confirmed_by uuid references public.profiles(id) on delete set null,
  confirmed_at timestamptz,
  cancelled_reason text,
  completed_at timestamptz
);

create table if not exists public.booking_driver_assignments (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.package_bookings(id) on delete cascade,
  driver_id uuid not null references public.profiles(id) on delete restrict,
  assigned_by uuid references public.profiles(id) on delete set null,
  status text not null default 'assigned',
  assigned_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.package_bookings(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  amount numeric(12,2) not null default 0,
  payment_method text not null,
  payment_status text not null default 'pending',
  payment_reference text,
  checkout_url text,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.driver_applications (
  id bigint generated by default as identity primary key,
  driver_id uuid not null references public.profiles(id) on delete cascade,
  city text not null,
  status text not null default 'pending',
  submitted_at timestamptz not null default now(),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  rejection_reason text
);

create table if not exists public.driver_details (
  driver_id uuid primary key references public.profiles(id) on delete cascade,
  mobile text,
  license_number text,
  plate_number text,
  license_expiry date,
  toda_name text,
  operator_code text,
  created_at timestamptz not null default now(),
  status text not null default 'pending',
  approved_by uuid references public.profiles(id) on delete set null,
  approved_at timestamptz,
  suspended_reason text
);

create table if not exists public.driver_documents (
  driver_id uuid primary key references public.profiles(id) on delete cascade,
  selfie_url text,
  license_front_url text,
  license_back_url text,
  police_clearance_url text,
  mtop_url text,
  vehicle_front_url text,
  vehicle_back_url text,
  vehicle_left_url text,
  vehicle_right_url text,
  or_url text,
  cr_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.rides (
  id bigint generated by default as identity primary key,
  tourist_id uuid references public.profiles(id) on delete set null,
  driver_id uuid references public.profiles(id) on delete set null,
  pickup_name text,
  pickup_lat double precision,
  pickup_lng double precision,
  dropoff_name text,
  dropoff_lat double precision,
  dropoff_lng double precision,
  distance_km numeric(10,2),
  fare_amount numeric(12,2),
  payment_method text,
  status text not null default 'requested',
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  driver_lat double precision,
  driver_lng double precision,
  driver_last_seen timestamptz
);

create table if not exists public.ride_feedback (
  id bigint generated by default as identity primary key,
  ride_id bigint not null references public.rides(id) on delete cascade,
  tourist_id uuid references public.profiles(id) on delete set null,
  driver_id uuid references public.profiles(id) on delete set null,
  rating numeric(2,1) not null,
  comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ride_reviews (
  id bigint generated by default as identity primary key,
  ride_id bigint not null references public.rides(id) on delete cascade,
  tourist_id uuid references public.profiles(id) on delete set null,
  driver_id uuid references public.profiles(id) on delete set null,
  rating numeric(2,1) not null,
  comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.saved_places (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  label text not null,
  address text,
  latitude double precision,
  longitude double precision,
  kind text,
  tag text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text,
  type text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.city_announcements (
  id bigint generated by default as identity primary key,
  created_by uuid references public.profiles(id) on delete set null,
  city text not null,
  title text not null,
  body text,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tourism_policies (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  status text not null default 'draft',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_role_city_idx on public.profiles(role, city);
create index if not exists tourist_spots_city_status_idx on public.tourist_spots(city, status, verification_status);
create index if not exists tourist_spot_views_spot_created_idx on public.tourist_spot_views(spot_id, created_at desc);
create index if not exists tour_packages_city_status_idx on public.tour_packages(city, status, visibility_status);
create index if not exists tour_package_views_package_created_idx on public.tour_package_views(package_id, created_at desc);
create index if not exists package_bookings_package_status_idx on public.package_bookings(package_id, status, created_at desc);
create index if not exists package_bookings_tourist_idx on public.package_bookings(tourist_id, created_at desc);
create index if not exists payments_booking_user_idx on public.payments(booking_id, user_id);
create index if not exists rides_tourist_idx on public.rides(tourist_id, created_at desc);
create index if not exists rides_driver_idx on public.rides(driver_id, created_at desc);
create index if not exists saved_places_user_idx on public.saved_places(user_id, updated_at desc);
create index if not exists notifications_user_idx on public.notifications(user_id, is_read, created_at desc);
create index if not exists audit_logs_actor_created_idx on public.audit_logs(actor_id, created_at desc);

drop trigger if exists set_admin_settings_updated_at on public.admin_settings;
create trigger set_admin_settings_updated_at before update on public.admin_settings
for each row execute function public.set_updated_at();

drop trigger if exists set_subtenant_details_updated_at on public.subtenant_details;
create trigger set_subtenant_details_updated_at before update on public.subtenant_details
for each row execute function public.set_updated_at();

drop trigger if exists set_tourism_categories_updated_at on public.tourism_categories;
create trigger set_tourism_categories_updated_at before update on public.tourism_categories
for each row execute function public.set_updated_at();

drop trigger if exists set_tourist_spots_updated_at on public.tourist_spots;
create trigger set_tourist_spots_updated_at before update on public.tourist_spots
for each row execute function public.set_updated_at();

drop trigger if exists set_tour_packages_updated_at on public.tour_packages;
create trigger set_tour_packages_updated_at before update on public.tour_packages
for each row execute function public.set_updated_at();

drop trigger if exists set_package_bookings_updated_at on public.package_bookings;
create trigger set_package_bookings_updated_at before update on public.package_bookings
for each row execute function public.set_updated_at();

drop trigger if exists set_ride_feedback_updated_at on public.ride_feedback;
create trigger set_ride_feedback_updated_at before update on public.ride_feedback
for each row execute function public.set_updated_at();

drop trigger if exists set_ride_reviews_updated_at on public.ride_reviews;
create trigger set_ride_reviews_updated_at before update on public.ride_reviews
for each row execute function public.set_updated_at();

drop trigger if exists set_saved_places_updated_at on public.saved_places;
create trigger set_saved_places_updated_at before update on public.saved_places
for each row execute function public.set_updated_at();

drop trigger if exists set_city_announcements_updated_at on public.city_announcements;
create trigger set_city_announcements_updated_at before update on public.city_announcements
for each row execute function public.set_updated_at();

drop trigger if exists set_tourism_policies_updated_at on public.tourism_policies;
create trigger set_tourism_policies_updated_at before update on public.tourism_policies
for each row execute function public.set_updated_at();

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace function public.current_profile_city()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select city from public.profiles where id = auth.uid()
$$;

alter table public.profiles enable row level security;
alter table public.admin_settings enable row level security;
alter table public.audit_logs enable row level security;
alter table public.city_tenant_registrations enable row level security;
alter table public.subtenant_details enable row level security;
alter table public.tourism_categories enable row level security;
alter table public.tourist_spots enable row level security;
alter table public.tourist_spot_images enable row level security;
alter table public.tourist_spot_views enable row level security;
alter table public.tour_packages enable row level security;
alter table public.tour_package_spots enable row level security;
alter table public.tour_package_days enable row level security;
alter table public.tour_package_day_items enable row level security;
alter table public.tour_package_views enable row level security;
alter table public.package_bookings enable row level security;
alter table public.booking_driver_assignments enable row level security;
alter table public.payments enable row level security;
alter table public.driver_applications enable row level security;
alter table public.driver_details enable row level security;
alter table public.driver_documents enable row level security;
alter table public.rides enable row level security;
alter table public.ride_feedback enable row level security;
alter table public.ride_reviews enable row level security;
alter table public.saved_places enable row level security;
alter table public.notifications enable row level security;
alter table public.city_announcements enable row level security;
alter table public.tourism_policies enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select using (
  id = auth.uid()
  or public.current_profile_role() = 'admin'
  or (
    public.current_profile_role() = 'subtenant'
    and city = public.current_profile_city()
  )
);

drop policy if exists profiles_update_self_or_admin on public.profiles;
create policy profiles_update_self_or_admin on public.profiles
for update using (id = auth.uid() or public.current_profile_role() = 'admin')
with check (id = auth.uid() or public.current_profile_role() = 'admin');

drop policy if exists own_settings on public.admin_settings;
create policy own_settings on public.admin_settings
for all using (user_id = auth.uid() or public.current_profile_role() = 'admin')
with check (user_id = auth.uid() or public.current_profile_role() = 'admin');

drop policy if exists audit_select_admin_subtenant on public.audit_logs;
create policy audit_select_admin_subtenant on public.audit_logs
for select using (public.current_profile_role() in ('admin', 'subtenant'));

drop policy if exists audit_insert_authenticated on public.audit_logs;
create policy audit_insert_authenticated on public.audit_logs
for insert with check (auth.uid() is not null);

drop policy if exists categories_read_authenticated on public.tourism_categories;
create policy categories_read_authenticated on public.tourism_categories
for select using (auth.uid() is not null);

drop policy if exists categories_admin_write on public.tourism_categories;
create policy categories_admin_write on public.tourism_categories
for all using (public.current_profile_role() = 'admin')
with check (public.current_profile_role() = 'admin');

drop policy if exists subtenant_details_select on public.subtenant_details;
create policy subtenant_details_select on public.subtenant_details
for select using (
  is_active = true
  or id = auth.uid()
  or public.current_profile_role() = 'admin'
  or (
    public.current_profile_role() = 'subtenant'
    and city = public.current_profile_city()
  )
);

drop policy if exists subtenant_details_write on public.subtenant_details;
create policy subtenant_details_write on public.subtenant_details
for all using (id = auth.uid() or public.current_profile_role() = 'admin')
with check (id = auth.uid() or public.current_profile_role() = 'admin');

drop policy if exists spots_read on public.tourist_spots;
create policy spots_read on public.tourist_spots
for select using (
  status <> 'archived'
  or public.current_profile_role() = 'admin'
  or (
    public.current_profile_role() = 'subtenant'
    and city = public.current_profile_city()
  )
);

drop policy if exists spots_write_admin_subtenant on public.tourist_spots;
create policy spots_write_admin_subtenant on public.tourist_spots
for all using (
  public.current_profile_role() = 'admin'
  or (
    public.current_profile_role() = 'subtenant'
    and city = public.current_profile_city()
  )
)
with check (
  public.current_profile_role() = 'admin'
  or (
    public.current_profile_role() = 'subtenant'
    and city = public.current_profile_city()
  )
);

drop policy if exists spot_images_read on public.tourist_spot_images;
create policy spot_images_read on public.tourist_spot_images
for select using (auth.uid() is not null);

drop policy if exists spot_images_write_admin_subtenant on public.tourist_spot_images;
create policy spot_images_write_admin_subtenant on public.tourist_spot_images
for all using (
  public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.tourist_spots s
    where s.id = spot_id and s.city = public.current_profile_city()
  )
)
with check (
  public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.tourist_spots s
    where s.id = spot_id and s.city = public.current_profile_city()
  )
);

drop policy if exists spot_views_insert_authenticated on public.tourist_spot_views;
create policy spot_views_insert_authenticated on public.tourist_spot_views
for insert with check (auth.uid() is not null and (user_id is null or user_id = auth.uid()));

drop policy if exists spot_views_select_admin_subtenant on public.tourist_spot_views;
create policy spot_views_select_admin_subtenant on public.tourist_spot_views
for select using (
  public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.tourist_spots s
    where s.id = spot_id and s.city = public.current_profile_city()
  )
);

drop policy if exists packages_read on public.tour_packages;
create policy packages_read on public.tour_packages
for select using (
  (status = 'published' and visibility_status = 'visible')
  or public.current_profile_role() = 'admin'
  or (
    public.current_profile_role() = 'subtenant'
    and city = public.current_profile_city()
  )
);

drop policy if exists packages_write_admin_subtenant on public.tour_packages;
create policy packages_write_admin_subtenant on public.tour_packages
for all using (
  public.current_profile_role() = 'admin'
  or (
    public.current_profile_role() = 'subtenant'
    and city = public.current_profile_city()
  )
)
with check (
  public.current_profile_role() = 'admin'
  or (
    public.current_profile_role() = 'subtenant'
    and city = public.current_profile_city()
  )
);

drop policy if exists package_children_read on public.tour_package_days;
create policy package_children_read on public.tour_package_days
for select using (auth.uid() is not null);

drop policy if exists package_days_write_admin_subtenant on public.tour_package_days;
create policy package_days_write_admin_subtenant on public.tour_package_days
for all using (
  public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.tour_packages p
    where p.id = package_id and p.city = public.current_profile_city()
  )
)
with check (
  public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.tour_packages p
    where p.id = package_id and p.city = public.current_profile_city()
  )
);

drop policy if exists package_day_items_read on public.tour_package_day_items;
create policy package_day_items_read on public.tour_package_day_items
for select using (auth.uid() is not null);

drop policy if exists package_day_items_write_admin_subtenant on public.tour_package_day_items;
create policy package_day_items_write_admin_subtenant on public.tour_package_day_items
for all using (
  public.current_profile_role() = 'admin'
  or exists (
    select 1
    from public.tour_package_days d
    join public.tour_packages p on p.id = d.package_id
    where d.id = day_id and p.city = public.current_profile_city()
  )
)
with check (
  public.current_profile_role() = 'admin'
  or exists (
    select 1
    from public.tour_package_days d
    join public.tour_packages p on p.id = d.package_id
    where d.id = day_id and p.city = public.current_profile_city()
  )
);

drop policy if exists package_spots_read on public.tour_package_spots;
create policy package_spots_read on public.tour_package_spots
for select using (auth.uid() is not null);

drop policy if exists package_spots_write_admin_subtenant on public.tour_package_spots;
create policy package_spots_write_admin_subtenant on public.tour_package_spots
for all using (
  public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.tour_packages p
    where p.id = package_id and p.city = public.current_profile_city()
  )
)
with check (
  public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.tour_packages p
    where p.id = package_id and p.city = public.current_profile_city()
  )
);

drop policy if exists package_views_insert_authenticated on public.tour_package_views;
create policy package_views_insert_authenticated on public.tour_package_views
for insert with check (auth.uid() is not null and (user_id is null or user_id = auth.uid()));

drop policy if exists package_views_select_admin_subtenant on public.tour_package_views;
create policy package_views_select_admin_subtenant on public.tour_package_views
for select using (
  public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.tour_packages p
    where p.id = package_id and p.city = public.current_profile_city()
  )
);

drop policy if exists package_bookings_select on public.package_bookings;
create policy package_bookings_select on public.package_bookings
for select using (
  tourist_id = auth.uid()
  or assigned_driver_id = auth.uid()
  or public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.tour_packages p
    where p.id = package_id and p.city = public.current_profile_city()
  )
);

drop policy if exists package_bookings_insert_tourist on public.package_bookings;
create policy package_bookings_insert_tourist on public.package_bookings
for insert with check (tourist_id = auth.uid());

drop policy if exists package_bookings_update_staff_or_owner on public.package_bookings;
create policy package_bookings_update_staff_or_owner on public.package_bookings
for update using (
  tourist_id = auth.uid()
  or public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.tour_packages p
    where p.id = package_id and p.city = public.current_profile_city()
  )
)
with check (
  tourist_id = auth.uid()
  or public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.tour_packages p
    where p.id = package_id and p.city = public.current_profile_city()
  )
);

drop policy if exists own_saved_places on public.saved_places;
create policy own_saved_places on public.saved_places
for all using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists own_notifications on public.notifications;
create policy own_notifications on public.notifications
for select using (user_id = auth.uid() or public.current_profile_role() = 'admin');

drop policy if exists notifications_insert_staff on public.notifications;
create policy notifications_insert_staff on public.notifications
for insert with check (public.current_profile_role() in ('admin', 'subtenant'));

drop policy if exists notifications_update_own on public.notifications;
create policy notifications_update_own on public.notifications
for update using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists payments_select on public.payments;
create policy payments_select on public.payments
for select using (
  user_id = auth.uid()
  or public.current_profile_role() = 'admin'
  or exists (
    select 1
    from public.package_bookings b
    join public.tour_packages p on p.id = b.package_id
    where b.id = booking_id and p.city = public.current_profile_city()
  )
);

drop policy if exists payments_insert_owner on public.payments;
create policy payments_insert_owner on public.payments
for insert with check (user_id = auth.uid() or public.current_profile_role() in ('admin', 'subtenant'));

drop policy if exists driver_profiles_select_staff_or_owner on public.driver_details;
create policy driver_profiles_select_staff_or_owner on public.driver_details
for select using (
  driver_id = auth.uid()
  or public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.profiles p
    where p.id = driver_id and p.city = public.current_profile_city()
  )
);

drop policy if exists driver_details_write on public.driver_details;
create policy driver_details_write on public.driver_details
for all using (driver_id = auth.uid() or public.current_profile_role() in ('admin', 'subtenant'))
with check (driver_id = auth.uid() or public.current_profile_role() in ('admin', 'subtenant'));

drop policy if exists driver_documents_select_staff_or_owner on public.driver_documents;
create policy driver_documents_select_staff_or_owner on public.driver_documents
for select using (
  driver_id = auth.uid()
  or public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.profiles p
    where p.id = driver_id and p.city = public.current_profile_city()
  )
);

drop policy if exists driver_documents_write_owner on public.driver_documents;
create policy driver_documents_write_owner on public.driver_documents
for all using (driver_id = auth.uid() or public.current_profile_role() in ('admin', 'subtenant'))
with check (driver_id = auth.uid() or public.current_profile_role() in ('admin', 'subtenant'));

drop policy if exists driver_applications_select on public.driver_applications;
create policy driver_applications_select on public.driver_applications
for select using (
  driver_id = auth.uid()
  or public.current_profile_role() = 'admin'
  or (public.current_profile_role() = 'subtenant' and city = public.current_profile_city())
);

drop policy if exists driver_applications_write on public.driver_applications;
create policy driver_applications_write on public.driver_applications
for all using (
  driver_id = auth.uid()
  or public.current_profile_role() = 'admin'
  or (public.current_profile_role() = 'subtenant' and city = public.current_profile_city())
)
with check (
  driver_id = auth.uid()
  or public.current_profile_role() = 'admin'
  or (public.current_profile_role() = 'subtenant' and city = public.current_profile_city())
);

drop policy if exists rides_select_participants_staff on public.rides;
create policy rides_select_participants_staff on public.rides
for select using (
  tourist_id = auth.uid()
  or driver_id = auth.uid()
  or public.current_profile_role() = 'admin'
  or exists (
    select 1 from public.profiles p
    where p.id = driver_id and p.city = public.current_profile_city()
  )
);

drop policy if exists rides_write_participants on public.rides;
create policy rides_write_participants on public.rides
for all using (
  tourist_id = auth.uid()
  or driver_id = auth.uid()
  or public.current_profile_role() = 'admin'
)
with check (
  tourist_id = auth.uid()
  or driver_id = auth.uid()
  or public.current_profile_role() = 'admin'
);

drop policy if exists ride_reviews_select_staff_or_participants on public.ride_reviews;
create policy ride_reviews_select_staff_or_participants on public.ride_reviews
for select using (
  tourist_id = auth.uid()
  or driver_id = auth.uid()
  or public.current_profile_role() in ('admin', 'subtenant')
);

drop policy if exists ride_reviews_insert_tourist on public.ride_reviews;
create policy ride_reviews_insert_tourist on public.ride_reviews
for insert with check (tourist_id = auth.uid());

drop policy if exists ride_feedback_select_staff_or_participants on public.ride_feedback;
create policy ride_feedback_select_staff_or_participants on public.ride_feedback
for select using (
  tourist_id = auth.uid()
  or driver_id = auth.uid()
  or public.current_profile_role() in ('admin', 'subtenant')
);

drop policy if exists ride_feedback_insert_tourist on public.ride_feedback;
create policy ride_feedback_insert_tourist on public.ride_feedback
for insert with check (tourist_id = auth.uid());

drop policy if exists announcements_select on public.city_announcements;
create policy announcements_select on public.city_announcements
for select using (
  status = 'published'
  or public.current_profile_role() = 'admin'
  or (public.current_profile_role() = 'subtenant' and city = public.current_profile_city())
);

drop policy if exists announcements_write_subtenant_admin on public.city_announcements;
create policy announcements_write_subtenant_admin on public.city_announcements
for all using (
  public.current_profile_role() = 'admin'
  or (public.current_profile_role() = 'subtenant' and city = public.current_profile_city())
)
with check (
  public.current_profile_role() = 'admin'
  or (public.current_profile_role() = 'subtenant' and city = public.current_profile_city())
);

drop policy if exists policies_select_published_staff on public.tourism_policies;
create policy policies_select_published_staff on public.tourism_policies
for select using (status = 'published' or public.current_profile_role() = 'admin');

drop policy if exists policies_admin_write on public.tourism_policies;
create policy policies_admin_write on public.tourism_policies
for all using (public.current_profile_role() = 'admin')
with check (public.current_profile_role() = 'admin');

drop policy if exists registrations_select on public.city_tenant_registrations;
create policy registrations_select on public.city_tenant_registrations
for select using (user_id = auth.uid() or public.current_profile_role() = 'admin');

drop policy if exists registrations_insert_owner on public.city_tenant_registrations;
create policy registrations_insert_owner on public.city_tenant_registrations
for insert with check (user_id = auth.uid());

drop policy if exists registrations_admin_update on public.city_tenant_registrations;
create policy registrations_admin_update on public.city_tenant_registrations
for update using (public.current_profile_role() = 'admin')
with check (public.current_profile_role() = 'admin');

drop policy if exists assignments_select on public.booking_driver_assignments;
create policy assignments_select on public.booking_driver_assignments
for select using (
  driver_id = auth.uid()
  or assigned_by = auth.uid()
  or public.current_profile_role() = 'admin'
  or exists (
    select 1
    from public.package_bookings b
    join public.tour_packages p on p.id = b.package_id
    where b.id = booking_id and p.city = public.current_profile_city()
  )
);

drop policy if exists assignments_write_staff on public.booking_driver_assignments;
create policy assignments_write_staff on public.booking_driver_assignments
for all using (
  public.current_profile_role() = 'admin'
  or exists (
    select 1
    from public.package_bookings b
    join public.tour_packages p on p.id = b.package_id
    where b.id = booking_id and p.city = public.current_profile_city()
  )
)
with check (
  public.current_profile_role() = 'admin'
  or exists (
    select 1
    from public.package_bookings b
    join public.tour_packages p on p.id = b.package_id
    where b.id = booking_id and p.city = public.current_profile_city()
  )
);
