alter table public.tourist_spots
  add column if not exists address text,
  add column if not exists municipality text,
  add column if not exists source_type text not null default 'manual',
  add column if not exists google_place_id text,
  add column if not exists google_photo_reference text;

update public.tourist_spots
set
  municipality = coalesce(nullif(municipality, ''), city),
  source_type = coalesce(nullif(source_type, ''), 'manual');

create index if not exists tourist_spots_municipality_idx
  on public.tourist_spots(municipality);

create index if not exists tourist_spots_source_type_idx
  on public.tourist_spots(source_type);

create index if not exists tourist_spots_google_place_id_idx
  on public.tourist_spots(google_place_id)
  where google_place_id is not null;

create table if not exists public.customized_package_spots (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.package_bookings(id) on delete cascade,
  tourist_id uuid not null references public.profiles(id) on delete cascade,
  package_id bigint not null references public.tour_packages(id) on delete cascade,
  spot_id bigint references public.tourist_spots(id) on delete set null,
  action_type text not null default 'kept',
  source_type text not null default 'manual',
  google_place_id text,
  spot_title text not null,
  spot_address text,
  municipality text not null,
  barangay text,
  latitude double precision,
  longitude double precision,
  image_url text,
  additional_fee numeric(12,2) not null default 0,
  sort_order integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists customized_package_spots_booking_idx
  on public.customized_package_spots(booking_id, sort_order);

create index if not exists customized_package_spots_tourist_idx
  on public.customized_package_spots(tourist_id, created_at desc);

drop trigger if exists set_customized_package_spots_updated_at on public.customized_package_spots;
create trigger set_customized_package_spots_updated_at
before update on public.customized_package_spots
for each row execute function public.set_updated_at();

alter table public.customized_package_spots enable row level security;

drop policy if exists customized_package_spots_select on public.customized_package_spots;
create policy customized_package_spots_select on public.customized_package_spots
for select using (
  tourist_id = auth.uid()
  or public.current_profile_role() = 'admin'
  or (
    public.current_profile_role() = 'subtenant'
    and exists (
      select 1
      from public.tour_packages p
      where p.id = package_id
        and p.city = public.current_profile_city()
    )
  )
);

drop policy if exists customized_package_spots_insert on public.customized_package_spots;
create policy customized_package_spots_insert on public.customized_package_spots
for insert with check (
  tourist_id = auth.uid()
  or public.current_profile_role() = 'admin'
  or (
    public.current_profile_role() = 'subtenant'
    and exists (
      select 1
      from public.tour_packages p
      where p.id = package_id
        and p.city = public.current_profile_city()
    )
  )
);

drop policy if exists customized_package_spots_update on public.customized_package_spots;
create policy customized_package_spots_update on public.customized_package_spots
for update using (
  tourist_id = auth.uid()
  or public.current_profile_role() = 'admin'
)
with check (
  tourist_id = auth.uid()
  or public.current_profile_role() = 'admin'
);
