// Reproduce the checked-in seed; no network calls or live database writes.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
const source = readFileSync(new URL('bulacan.geojson', import.meta.url));
const { features } = JSON.parse(source);
const config = {
  Baliuag: ['ph-bul-baliwag', 'Baliwag', ['baliwag','baliuag','city of baliwag']],
  Bustos: ['ph-bul-bustos', 'Bustos', ['bustos']],
  'City of Malolos': ['ph-bul-malolos', 'Malolos', ['malolos','city of malolos']],
};
if (features.length !== 3) throw Error('Expected exactly three reviewed municipality features');
const quote = s => `'${s.replaceAll("'", "''")}'`;
let sql = `-- Generated by supabase/service_areas/build_seed.mjs. Do not edit coordinates here.
-- Source: geoBoundaries gbOpen PHL ADM3, commit 9469f09, represented year 2020.
-- NAMRIA / PSA / OCHA Philippines. CC BY 3.0 IGO; see service_areas/README.md.
-- Extract SHA256: ${createHash('sha256').update(source).digest('hex')}
begin;
`;
for (const f of features) {
  const c = config[f.properties.shapeName];
  if (!c) throw Error(`Unexpected municipality: ${f.properties.shapeName}`);
  sql += `insert into public.booking_service_areas(id,municipality,province,municipality_aliases,geometry,version,source_url,source_license) values (
${quote(c[0])},${quote(c[1])},'Bulacan',array[${c[2].map(quote).join(',')}],
${quote(JSON.stringify(f.geometry))}::jsonb,
'gbOpen-PHL-ADM3-9469f09-2020',
'https://github.com/wmgeolab/geoBoundaries/blob/9469f09/releaseData/gbOpen/PHL/ADM3/geoBoundaries-PHL-ADM3.geojson',
'CC BY 3.0 IGO; NAMRIA / PSA / OCHA Philippines; geoBoundaries')
on conflict(id) do nothing;
`;
}
sql += 'commit;\n';
writeFileSync(new URL('../migrations/20260926000001_booking_service_area_seed.sql', import.meta.url), sql);
